---
  - name: Upgrade packages.
    apt: upgrade=dist update_cache=yes

  - name: Install the latest Java 7.
    apt: name=openjdk-7-jdk state=latest install_recommends=no update_cache=yes

  - name: Copy hosts file.
    template: src=hosts.j2 dest=/etc/hosts backup=no owner=root group=root mode=0750

  - name: Copy environment file.
    copy: src=environment dest=/etc/environment backup=no owner=root group=root mode=0750

  - name: Generate ssh key.
    shell: cat /dev/zero | ssh-keygen -q -N ""
    args:
      creates: /root/.ssh/id_rsa.pub
