---
  - name: Include tasks for master.
    include: master.yml
    when: "'master' in group_names"
    tags:
      - master

  - name: Include tasks for all nodes.
    include: all.yml
    tags:
      - all
