---

  - hosts: master
    user: root
    roles:
      - ../roles/proxy

  - hosts: all
    user: root
    roles:
      - ../roles/common
      - ../roles/apache-hadoop
      - ../roles/apache-kafka
      - ../roles/apache-flink
