---
  - name: Install Apache kafka.
    include: install.yml

  - name: Configure Apache Zookeeper.
    template: src=zookeeper.properties.j2 dest="{{ installation_path }}/kafka/config/zookeeper.properties" owner=kafka group=lambda mode=0644
    tags:
      - configure-kafka

  - name: Configure Apache kafka.
    copy: src=server.properties dest="{{ installation_path }}/kafka/config/server.properties" owner=kafka group=lambda mode=0644
    tags:
      - configure-kafka

  - name: Start Apache Zookeeper server.
    shell: /etc/init.d/zookeeper-init start > /dev/null
    tags:
      - start-zookeeper

  - name: Wait for Apache Zookeeper to become available.
    wait_for: port=2181
    tags:
      - start-zookeeper

  - name: Start Apache Kafka server.
    shell: /etc/init.d/kafka-init start > /dev/null
    tags:
      - start-kafka

  - name: Wait for Apache Kafka server to become available.
    wait_for: port=9092 timeout=30
    changed_when: true
    notify:
      - create topics
    tags:
      - start-kafka
