---
  - name: Install Apache kafka.
    include: install.yml

  - name: Configure Apache kafka.
    template: src=server.properties.j2 dest="{{ installation_path }}/kafka/config/server.properties" owner=kafka group=lambda mode=0644
    tags:
      - configure-kafka

  - name: Start Apache Kafka server.
    supervisorctl: name=apache_kafka state=started
    tags:
      - start-kafka

  - name: Wait for Apache Kafka server to become available.
    wait_for: port=9092
    tags:
      - start-kafka
