---
  - name: Configure Apache kafka.
    template: src=usr/local/kafka/config/server.properties.j2 dest=/usr/local/kafka/config/server.properties owner=root group=root mode=0644
    tags:
      - configure-kafka

  - name: Start Apache Kafka server.
    shell: /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties
    async: 31536000 # Stay alive for a year(1 year = 31536000 seconds).
    poll: 0
    tags:
      - start-kafka

  - name: Wait for Apache Kafka server to become available.
    wait_for: port=9092
    tags:
      - start-kafka

