---
  - name: Install python-dev, sudo and git packages.
    apt: name={{ item }} state=latest
    with_items:
      - python-dev
      - sudo
      - git

  - name: Include apache2 tasks.
    include: apache-install.yml

  - name: Include postgresql-install tasks.
    include: postgresql-install.yml

  - name: Download Django code from Github.
    git: repo={{ repository_url }}  dest={{ repository_download_path }}/okeanos-LoD update=yes version={{ repository_branch }}

  - name: Change repository permissions.
    file: path={{ repository_download_path }} owner=celery group=celery recurse=yes

  - name: Install Fokia requirements.
    pip: requirements={{ repository_download_path }}/okeanos-LoD/core/requirements.txt

  - name: Install app requirements.
    pip: requirements={{ repository_download_path }}/okeanos-LoD/central_service/app/requirements.txt

  - name: Install Fokia.
    command: python setup.py install chdir="{{ repository_download_path }}/okeanos-LoD/core/"

  - name: Setup Django database configuration.
    template: src=settings.py.j2 dest={{ repository_download_path }}/okeanos-LoD/central_service/app/app/settings.py
    notify:
      - django_dbs_migrate
