---

- hosts: master
  user: root
  tasks:
    - include: ../tasks/apache-flink/download-flink.yml        tags=download
    - include: ../tasks/apache-flink/uncompress-flink.yml      tags=uncompress
    - include: ../tasks/apache-flink/create-softlink-flink.yml tags=uncompress
    - include: ../tasks/apache-flink/configure-flink.yml       tags=configure
    - include: ../tasks/apache-flink/start-flink.yml           tags=start-flink
