---

- name: Download hadoop from apache servers
  get_url: url=http://mirrors.myaegean.gr/apache/hadoop/common/hadoop-2.7.0/hadoop-2.7.0.tar.gz
           dest=/root/hadoop-2.7.0.tar.gz

- name: Untar hadoop
  unarchive: src=/root/hadoop-2.7.0.tar.gz copy=no
             dest=/usr/local/

- name: Make hadoop softlink
  file: src=/usr/local/hadoop-2.7.0 dest=/usr/local/hadoop state=link