---
  - name: Format Apache HDFS.
    shell: "yes | {{ installation_path }}/hadoop/bin/hadoop namenode -format"
    tags:
      - format-hdfs

  - name: Start Apache HDFS.
    shell: /etc/init.d/hdfs-init start # Should use Ansible module "service: name=hdfs-init state=started" when the bug in version 1.9.1 is fixed.
    tags:
      - start-hdfs

  - name: Start Apache Yarn.
    shell: /etc/init.d/yarn-init start # Should use Ansible module "service: name=yarn-init state=started" when the bug in version 1.9.1 is fixed.
    tags:
      - start-yarn

  - name: Create Apache HDFS user directory.
    command: "{{ installation_path }}/hadoop/bin/hadoop fs -mkdir /user"
    tags:
      - create-dirs

  - name: Create Apache HDFS user/root directory. 
    command: "{{ installation_path }}/hadoop/bin/hadoop fs -mkdir /user/root"
    tags:
      - create-dirs

