---

  - hosts: master
    user: root
    gather_facts: no
    roles:
      - wait_for_ssh

  - hosts: master
    user: root
    roles:
      - proxy

  - hosts: all
    user: root
    roles:
      - common
      - apache-hadoop
      - apache-kafka
      - apache-flink
