---
  - name: Download Apache Flink, Yarn version.
    get_url: url="{{ mirror_url }}/flink-{{ version }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz"
    tags:
      - download

  - name: Uncompress Apache Flink.
    unarchive: src="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ installation_path }}" copy=no owner=flink group=lambda
    tags:
      - uncompress

  - name: Create softlink for Apache Flink.
    file: src="{{ installation_path }}/flink-{{ version }}" dest="{{ installation_path }}/flink" state=link
    tags:
      - uncompress

  - name: Configure Apache Flink.
    template: src=flink-conf.j2 dest="{{ installation_path }}/flink/conf/flink-conf.yaml" owner=flink group=lambda mode=0644
    tags:
      - configure

  - name: Start Apache Flink.
    shell: "{{ installation_path }}/flink/bin/yarn-session.sh -n {{ number_of_taskmanagers }} -tm {{ ram_per_task_manager }}"
    async: 31536000 # Stay alive for a year(1 year = 31536000 seconds).
    poll: 0
    tags:
      - start
