---

  - name: Download Apache Flink, Yarn version.
    get_url: url="{{ mirror_url }}/flink-{{ version }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz"
    environment: proxy_env 
    tags:
      - download

  - name: Uncompress Apache Flink.
    unarchive: src="{{ download_path }}/flink-{{ version }}-{{ version_for }}.tgz" dest="{{ installation_path }}" copy=no owner=flink group=lambda
    tags:
      - uncompress

  - name: Create softlink for Apache Flink.
    file: src="{{ installation_path }}/flink-{{ version }}" dest="{{ installation_path }}/flink" state=link
    tags:
      - uncompress

  - name: Configure Apache Flink.
    template: src=flink-conf.j2 dest="{{ installation_path }}/flink/conf/flink-conf.yaml" owner=flink group=lambda mode=0644
    tags:
      - configure

  - name: Copy run_batch_job script
    copy: src=run_batch_job.sh dest="/home/flink/run_batch_job.sh" owner=flink group=flink mode=0744
    tags:
      - configure

  - name: Copy run_streaming_job script
    copy: src=run_streaming_job.sh dest="/home/flink/run_streaming_job.sh" owner=flink group=flink mode=0744
    tags:
      - configure

  - name: Start Apache Flink.
    supervisorctl: name=apache_flink state=started
    tags:
      - start
