---

  - name: Install squid http proxy
    apt: name=squid3 state=latest
    tags: install

  - name: Configure squid http proxy 1
    lineinfile: destfile="/etc/squid3/squid.conf" regexp="^acl localnet" insertafter="^#acl localnet"
                line="acl localnet src {{ hostvars[groups['all'][0]]['local_net'] }}"
                state=present
    tags: config
    
  - name: Configure squid http proxy 2
    lineinfile: destfile="/etc/squid3/squid.conf" regexp="^#http_access allow localnet"
                line="http_access allow localnet"
                state=present
    tags: config

